import { AppState } from "./types";

const now = new Date().toISOString();

export const seedState: AppState = {
  users: [
    {
      id: 1,
      name: "System Admin",
      email: "admin@gmail.com",
      password: "admin123",
      role: "admin",
      status: "active",
    },
    {
      id: 2,
      name: "Default Student",
      email: "student@gmail.com",
      password: "student123",
      role: "student",
      status: "active",
      studentNumber: "S202600002",
    },
    {
      id: 3,
      name: "Maria Santos",
      email: "maria.santos@gmail.com",
      password: "student123",
      role: "student",
      status: "active",
      studentNumber: "S202600003",
    },
    {
      id: 4,
      name: "Juan Dela Cruz",
      email: "juan.delacruz@gmail.com",
      password: "student123",
      role: "student",
      status: "active",
      studentNumber: "S202600004",
    },
    {
      id: 5,
      name: "Ana Reyes",
      email: "ana.reyes@gmail.com",
      password: "student123",
      role: "student",
      status: "inactive",
    },
  ],
  courses: [
    { id: 1, code: "BSIT", name: "BS Information Technology", capacity: 120, department: "Computing" },
    { id: 2, code: "BSBA", name: "BS Business Administration", capacity: 100, department: "Business" },
    { id: 3, code: "BSED", name: "BS Secondary Education", capacity: 90, department: "Education" },
  ],
  subjects: [
    { id: 1, courseId: 1, code: "IT101", name: "Introduction to Computing", units: 3 },
    { id: 2, courseId: 1, code: "IT102", name: "Programming Fundamentals", units: 3, prerequisite: "IT101" },
    { id: 3, courseId: 1, code: "IT103", name: "Database Systems", units: 3, prerequisite: "IT102" },
    { id: 4, courseId: 1, code: "IT104", name: "Web Development", units: 3, prerequisite: "IT102" },
    { id: 5, courseId: 2, code: "BA101", name: "Principles of Management", units: 3 },
    { id: 6, courseId: 3, code: "ED101", name: "Foundations of Education", units: 3 },
  ],
  sections: [
    { id: 1, subjectId: 1, name: "A", schedule: "Mon-Wed 8:00-9:30 AM", room: "Lab 201", studentLimit: 40 },
    { id: 5, subjectId: 1, name: "B", schedule: "Tue-Thu 9:00-10:30 AM", room: "Lab 204", studentLimit: 40 },
    { id: 2, subjectId: 2, name: "A", schedule: "Mon-Wed 10:00-11:30 AM", room: "Lab 203", studentLimit: 35 },
    { id: 6, subjectId: 2, name: "B", schedule: "Tue-Thu 10:30-12:00 NN", room: "Lab 205", studentLimit: 35 },
    { id: 3, subjectId: 3, name: "A", schedule: "Tue-Thu 1:00-2:30 PM", room: "Lab 202", studentLimit: 40 },
    { id: 4, subjectId: 5, name: "A", schedule: "Fri 9:00-12:00 NN", room: "Room 305", studentLimit: 50 },
    { id: 7, subjectId: 6, name: "A", schedule: "Mon 1:00-4:00 PM", room: "Room 110", studentLimit: 45 },
  ],
  enrollments: [
    { id: 1, userId: 2, courseId: 1, status: "approved", submittedAt: now, updatedAt: now },
    { id: 2, userId: 3, courseId: 2, status: "pending", submittedAt: now, updatedAt: now },
    { id: 3, userId: 4, courseId: 1, status: "enrolled", submittedAt: now, updatedAt: now },
    { id: 4, userId: 5, courseId: 3, status: "rejected", submittedAt: now, updatedAt: now },
  ],
  enrollmentSubjects: [
    { id: 1, enrollmentId: 1, subjectId: 1, sectionId: 1 },
    { id: 2, enrollmentId: 1, subjectId: 2, sectionId: 2 },
    { id: 3, enrollmentId: 1, subjectId: 3, sectionId: 3 },
    { id: 4, enrollmentId: 2, subjectId: 5, sectionId: 4 },
    { id: 5, enrollmentId: 3, subjectId: 1, sectionId: 5 },
    { id: 6, enrollmentId: 3, subjectId: 2, sectionId: 6 },
    { id: 7, enrollmentId: 3, subjectId: 4 },
    { id: 8, enrollmentId: 4, subjectId: 6, sectionId: 7 },
  ],
  payments: [
    {
      id: 1,
      userId: 2,
      enrollmentId: 1,
      amount: 18500,
      paymentType: "tuition",
      paymentMethod: "gcash",
      referenceNo: "GCASH-DEMO-001",
      payerName: "Default Student",
      paymentDate: new Date().toISOString().slice(0, 10),
      proof: "receipt_tuition_may.pdf",
      remarks: "Initial tuition payment",
      status: "confirmed",
      paidAt: now,
    },
    {
      id: 2,
      userId: 2,
      enrollmentId: 1,
      amount: 2500,
      paymentType: "miscellaneous",
      paymentMethod: "bank_transfer",
      referenceNo: "BNK-DEMO-002",
      payerName: "Default Student",
      paymentDate: new Date().toISOString().slice(0, 10),
      proof: "receipt_misc_pending.jpg",
      remarks: "Lab fee pending",
      status: "pending",
      paidAt: now,
    },
    {
      id: 3,
      userId: 3,
      enrollmentId: 2,
      amount: 12000,
      paymentType: "tuition",
      paymentMethod: "paymaya",
      referenceNo: "PAYMAYA-DEMO-003",
      payerName: "Maria Santos",
      paymentDate: new Date().toISOString().slice(0, 10),
      proof: "maria_tuition.png",
      remarks: "Waiting for admin confirmation",
      status: "pending",
      paidAt: now,
    },
    {
      id: 4,
      userId: 4,
      enrollmentId: 3,
      amount: 18000,
      paymentType: "tuition",
      paymentMethod: "bank_transfer",
      referenceNo: "BNK-DEMO-004",
      payerName: "Juan Dela Cruz",
      paymentDate: new Date().toISOString().slice(0, 10),
      proof: "juan_tuition.pdf",
      remarks: "Validated by cashier",
      status: "confirmed",
      paidAt: now,
    },
    {
      id: 5,
      userId: 5,
      enrollmentId: 4,
      amount: 5000,
      paymentType: "enrollment_fee",
      paymentMethod: "gcash",
      referenceNo: "GCASH-DEMO-005",
      payerName: "Ana Reyes",
      paymentDate: new Date().toISOString().slice(0, 10),
      proof: "ana_fee.jpg",
      remarks: "Rejected due to invalid proof",
      status: "rejected",
      paidAt: now,
    },
  ],
  announcements: [
    { id: 1, title: "Enrollment Open", body: "Enrollment is now open for all incoming and continuing students.", targetRole: "all", createdAt: now },
    { id: 2, title: "Payment Reminder", body: "Submit your payment details before final enrollment confirmation.", targetRole: "student", createdAt: now },
    { id: 3, title: "Admin Meeting", body: "Admin team meeting on Friday 4PM.", targetRole: "admin", createdAt: now },
    { id: 4, title: "Class Suspension Advisory", body: "Face-to-face classes are suspended on Monday due to weather conditions.", targetRole: "all", createdAt: now },
    { id: 5, title: "Section Encoding Deadline", body: "Admins must finalize section assignments before end of week.", targetRole: "admin", createdAt: now },
  ],
  notifications: [
    { id: 1, userId: 2, message: "Your enrollment has been approved.", isRead: false, createdAt: now },
    { id: 2, userId: 2, message: "Your payment has been confirmed.", isRead: true, createdAt: now },
    { id: 3, userId: 3, message: "Your enrollment request is pending admin review.", isRead: false, createdAt: now },
    { id: 4, userId: 4, message: "You are now officially enrolled.", isRead: true, createdAt: now },
    { id: 5, userId: 5, message: "Your enrollment was rejected. Please contact admissions.", isRead: false, createdAt: now },
  ],
  grades: [
    { id: 1, userId: 2, subjectId: 1, grade: "1.75", term: "2026-1st Semester" },
    { id: 2, userId: 2, subjectId: 2, grade: "2.00", term: "2026-1st Semester" },
    { id: 3, userId: 4, subjectId: 1, grade: "1.50", term: "2026-1st Semester" },
    { id: 4, userId: 4, subjectId: 2, grade: "1.75", term: "2026-1st Semester" },
  ],
  settings: {
    academicYear: "2026-2027",
    semester: "1st Semester",
  },
};
